server:
 port: 9000
spring:
 datasource:
  url: "jdbc:h2:mem:desafio"
  username: "softplan"
  password: "softplan"
  
 jpa:
   hibernate:
    ddl-auto: "update"
    show-sql: false
   properties:
    hibernate:
     jdbc:
      lob:
       non_contextual_creation: true
    format_sql: true   